<?= $this->escape($this->messages[0]) ?> 
<?php
function custom_echo($x)
{
  if(strlen($x)<=50)
  {
    echo $x;
  }
  else
  {
    $y=substr($x,0,50) . '...';
    echo $y;
  }
}?>
<center><form class="form-inline" action="<?=$this->url(array("controller"=>"mensagens","action"=>"index"),null,true)?>" method="post">
    <select name="campo">
        <option value="campo">Campo</option>
        <option value="date_">Data</option>
        <option value="number">Numero</option>
        <option value="msg">Texto</option>
        <option value="result">Resultado</option>
    </select>
    <select name="operador">
        <option value="operador">Operador</option>
        <option value="=">Igual a</option>
        <option value="<">Menor que</option>
        <option value="<=">Menor ou igual a</option>
        <option value=">">Maior que</option>
        <option value=">=">Maior ou igual a</option>
        <option value="LIKE">Parecido com</option>
    </select>
  <input type="text" name="valor" class="input-small" placeholder="Texto" autocomplete="off">
  <button type="submit" class="btn">Enviar</button>
  <a class="btn" href="<?=$this->url(array("controller"=>"mensagens","action"=>"index"),null,true)?>">Limpar Filtros</a>
</form>
</center>

<form class="form-search">
  <input type="text" class="input-medium search-query" value='A ser implementado'>
  <button type="submit" class="btn">Pesquisar</button>
</form>

<?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml'); ?>

<table class="table table-striped table-hover table-bordered table-condensed" width="100%" cellpadding="3" cellspacing="0" border="1">
   <tr>
        <th><center>Remetente</center></th>
        <th><center>Mensagem</center></th>                
        <th><center>Status</center></th>
        <th><center>Alterado por</center></th>
        <th><center>Data de recebimento</center></th>
        <th><center>Data de Alteraçao</center></th>
        <th><center>Açoes</center></th>
   </tr>
   <?php foreach($this->paginator AS $key => $mensagem):?>
   <tr>
      <td><center><?=$mensagem['nomeCliente']?></center></td>
<td><center><?=  custom_echo($mensagem['mensagem'])?></center></td>        
        <td><center><?=$mensagem['status']?></center></td>
        <td><center><?=$mensagem['nomeUsuario']?></center></td>
        <td><center><?=$mensagem['dataContato']?></center></td>
        <td><center><?=$mensagem['dataUpdt']?></center></td>
      <td><center>
         <a href="<?=$this->url(array("controller"=>"mensagens","action"=>"show","id"=>"{$mensagem['idContato']}"),null,true)?>" title="Visualizar Contato"><i class='icon-eye-open'> </i></a>
         <a href="<?=$this->url(array("controller"=>"mensagens","action"=>"edit","id"=>"{$mensagem['idContato']}"),null,true)?>" title="Editar Contato"><i class='icon-pencil'></i></a> 
         <a href="<?=$this->url(array("controller"=>"responder","action"=>"mensagem","id"=>"{$mensagem['idContato']}"),null,true)?>" title="Responder"><i class='icon-envelope'></i></a> 
         </center>
      </td>
   </tr>
   <?php endforeach;?>
</table>