<?=$this->doctype('HTML5')?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-br">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-Type" content="text/html; charset=iso" />
        <base href="http://<?=$_SERVER['HTTP_HOST'] . $this->baseUrl()?>/" />
        <title>BestWebFast</title>
        <?= $this->headTitle() ?>
        <?= $this->headLink()->appendStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl().'/media/css/bootstrap.css')?>
        <style>
            /*.span2{
box-shadow: 10px 10px 5px #888888;
border-radius:15px;
}*/
        </style>
    </head>
    
<!-- HEADER -->

<div class="page-header">
    <h1><img src = "<?=$this->baseUrl().'/media/img/logo.png'?>" width='5%' height='5%' alt = "BestWebFast" />
        <small>Controle Mensagens</small></h1>
    
    <div id="area_login">
                <table>
                    <tr>
                        <td>Ola <b><?=$this->layout()->usuario->nome; ?> <i class="icon-user"></i> </b></td>
                        <td><a href="<?=$this->url(array("controller"=>"index","action"=>"logout"),null,true)?>">Logout</a></td>
                    </tr>
                </table>
            </div>
</div>
<!-- HEADER -->

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span2">
      <!--Menu-->
          <ul class="nav nav-tabs nav-stacked bs-docs-sidenav affix">
            <li><a href="<?=$this->url(array("controller"=>"mensagens","action"=>"index"),null,true)?>">Mensagens</a></li>
            
            <?php if( $this->layout()->usuario->idGrupo == 1){?>
            <li><a>Administração</a></li>
            <li><a href="<?=$this->url(array("controller"=>"group","action"=>"index"),null,true)?>"><i class="icon-chevron-right"></i> Administrar Usuários</a></li>
            <li><a href="<?=$this->url(array("controller"=>"group","action"=>"new"),null,true)?>"><i class="icon-chevron-right"></i> Administrar grupos de usuários</a></li>
            <?php };?>
            <li><a>Grupos</a></li>
            <li><a href="<?=$this->url(array("controller"=>"group","action"=>"index"),null,true)?>"><i class="icon-chevron-right"></i> Exibir Todos</a></li>
            <li><a href="<?=$this->url(array("controller"=>"group","action"=>"new"),null,true)?>"><i class="icon-chevron-right"></i> Adicionar Grupo</a></li>
            <li><a>Sms</a></li>
            <li><a href="<?=$this->url(array("controller"=>"sms","action"=>"outgoing"),null,true)?>"><i class="icon-chevron-right"></i> Visualizar SMS's <br> enviadas</a></li>
            <li><a href="<?=$this->url(array("controller"=>"sms","action"=>"incoming"),null,true)?>"><i class="icon-chevron-right"></i> Visualizar SMS's <br>recebidas</a></li>
        </ul>
      
    </div>
    <div class="span10">
      <?php echo $this->layout()->content; ?>
    </div>
  </div>
</div>